import { ApiProperty } from '@nestjs/swagger';

export class RagResponseDto {
    @ApiProperty({
        description: 'The answer generated by the LLM',
        example: 'The document discusses the importance of RAG architectures...',
    })
    answer: string;

    @ApiProperty({
        description: 'List of sources used to generate the answer',
        example: [
            {
                text: 'RAG reduces hallucinations by grounding...',
                score: 0.85,
                metadata: { page: 1, source: 'whitepaper.pdf' },
            },
        ],
    })
    sources: any[];

    @ApiProperty({
        description: 'Number of context chunks used',
        example: 3,
    })
    contextUsed: number;
}
